import pytest

@pytest.mark.parametrize("name", [
  ("apt-file"),
  ("apt-transport-https"),
  ("atsar"),
  ("blktrace"),
  ("ca-certificates"),
  ("chromium-browser"),
  ("cron"),
  ("curl"),
  ("diod"),
  ("docker-engine"),
  ("git"),
  ("gnupg"),
  ("handbrake"),
  ("handbrake-cli"),
  ("haveged"),
  ("htop"),
  ("i3"),
  ("iotop"),
  ("language-pack-en-base"),
  ("laptop-mode-tools"),
  ("nfs-common"),
  ("ntop"),
  ("ntp"),
  ("openssh-client"),
  ("openssh-server"),
  ("openssh-sftp-server"),
  ("openssl"),
  ("python"),
  ("python-pip"),
  ("sysstat"),
  ("tree"),
  ("vagrant"),
  ("vim"),
  ("vim-addon-manager"),
  ("vim-puppet"),
  ("vim-syntax-docker"),
  ("virtualbox"),
  ("vlc"),
  ("wget"),
  ("whois"),
  ("x264"),
  ("xinit"),
])

def test_packages(Package, name):
  assert Package(name).is_installed
