# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "salttest" do |salttest|

    salttest.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    salttest.vm.box = "ubuntu/trusty64"
    salttest.vm.network "private_network", ip: "192.168.168.2"
    salttest.vm.hostname = "salt-test"
    salttest.vm.synced_folder "../salt/roots/", "/srv/salt/"
    salttest.vm.synced_folder "../salt/pillar/", "/srv/pillar/"

    salttest.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "../salt/minion"
      salt.run_highstate = true
    end

  end

end
