# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "salttest" do |salttest|

    salttest.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    salttest.vm.box = "ubuntu/trusty64"
    salttest.vm.network "private_network", ip: "192.168.168.2"
    salttest.vm.hostname = "salt-test"
    salttest.vm.synced_folder "../salt/roots/", "/srv/salt/"
    salttest.vm.synced_folder "../salt/pillar/", "/srv/pillar/"

    salttest.vm.provision :salt do |salt|
      salt.masterless = true
      salt.minion_config = "../salt/minion"
      salt.run_highstate = true
    end

  end

  config.vm.define "ansibletest" do |ansibletest|

    ansibletest.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end

    ansibletest.vm.box = "ubuntu/trusty64"
    ansibletest.vm.network "private_network", ip: "192.168.168.3"
    ansibletest.vm.hostname = "ansible-test"
    ansibletest.vm.synced_folder "../ansible/", "/srv/ansible/"

    ansibletest.vm.provision :ansible_local do |ansible|
      ansible.provisioning_path = "/srv/ansible/"
      ansible.inventory_path = "/srv/ansible/hosts"
      ansible.raw_arguments = "--verbose"
      ansible.limit = "ansible-test"
      ansible.playbook = "/srv/ansible/site.yml"
    end

  end

end
