- name: Create Users
  user:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('absent') }}"
    shell: "{{ item.value.shell | default('/bin/bash') }}"
    home: "{{ item.value.home | default('/home/' + item.key) }}"
    createhome: yes
    comment: "{{ item.value.comment | default('User') }}"
    password: "{{ item.value.password }}"
    update_password: always
  with_dict: "{{ users | default({}) }}"

- name: Modify Users
  user:
    name: "{{ item.key }}"
    groups: "{{ item.value.groups | join(',') }}"
  when: item.value.groups is defined
  with_dict: "{{ users | default({}) }}"

- name: Lock Down Home Directory
  file:
    path: "{{ item.value.home | default('/home/' + item.key) }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: 0750
  with_dict: "{{ users | default({}) }}"

- name: Remove standard Ubuntu home directories
  include: deldirs.yml user="{{ item.key }}" homedir="{{ item.value.home | default('/home/' + item.key) }}"
  with_dict: "{{ users | default({}) }}"
