- name: Vundle Vim Repo
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/wicksy/.vim/bundle/Vundle.vim"
    version: master
    clone: yes
    force: yes
    update: yes
  become_user: wicksy

- name: Install Vundle Plugins
  command: vim +PluginInstall +qall
  become_user: wicksy

- name: Chown vim directories and files (wicksy)
  file:
    path: /home/wicksy/.vim
    state: directory
    owner: wicksy
    group: wicksy
    mode: 0755
    recurse: yes
