- name: Install pips (pip2)
  pip:
    name: "{{ item }}"
    executable: pip2
    state: latest
  with_items:
    - "{{ core_pips | default([]) }}"

- name: Install pips (pip3)
  pip:
    name: "{{ item }}"
    executable: pip3
    state: latest
  with_items:
    - "{{ core_pips | default([]) }}"
